title: 流星企盼|Blog
author: 流星企盼
resume: false
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
permalink: '/:title/'
github: KiritoBeater
email: 1353137283@qq.com
width: large
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      category: blog
  - scope:
      path: ''
      type: drafts
    values:
      layout: post
      category: blog
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-optional-front-matter
compress_html:
  ignore:
    envs:
      - development
      - stage
include:
  - manifest.json
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - vendor
